---
output: html_document
---
# Getting setup with Rstudio, A Bash Shell, and GitHub

It might seem strange to start a bioinformatics course with a segment
on RStudio, since most bioinformatics takes place on large computer
clusters which can't always be configured by individual users to
play well with RStudio running on a server.  Not to mention the fact that
R is not typically central to hard-core bioinformatic tasks in a 
Unix environment.  However, bear with us.  Using RStudio sets you up
with a great mechanism for recording your work in RMarkdown Notebooks,
it provides a natural way to organize projects, it makes it trivial
to keep your work version-controlled, and finally, when you have done
all your bioinformatics, it is great for analysis of and figure preparation from
the generated data in the R language.

This week is mostly about getting everyone's laptop configured
to use RStudio, to compile RMarkdown documents, and to use git and GitHub which
are necessary for getting and submitting the homework assignments in this course.


---

## Lecture Slides

- [setting-up-your-system.html](slides-and-things/setting-up-your-system.html) (For Tuesday)
- [git-and-github.html](slides-and-things/git-and-github.html) (For Thursday)

## Required Readings {-}


1. Download the [RStudio IDE Cheat Sheet](https://github.com/rstudio/cheatsheets/raw/master/rstudio-ide.pdf).  Study it and keep it close by on your computer for frequent reference. (Read it Before/During Tuesday's class).
1. Download the [RStudio Rmarkdown Cheat Sheet](https://github.com/rstudio/cheatsheets/raw/master/rmarkdown-2.0.pdf) and peruse it before Wednesday's Computer lab session.


## Recommended Readings {-}

1. [Chapter 8 of _R for Data Science_](https://r4ds.had.co.nz/workflow-projects.html). A quick primer on RStudio projects and ways to configure RStudio.



## Exercises due by Friday January 24, 2020 at 5:00 PM {-}

1. You will be doing the exercises outlined in this [template repository](https://github.com/eriqande/rmarkdown-introduction).  **But students in the class, don't clone that and work from that repository**.  You will all get your own repositories to work on using GitHub Classroom.


---

