# Next generation sequencing and bioinformatic file formats

* Tuesday: DNA sequences and sequencing. FASTQ files.
* Thursday: FASTA and SAM formats.

---

## Required Readings {-}

1. [eca-bioinf-handbook 16.1 to 16.3](https://eriqande.github.io/eca-bioinf-handbook/dna-sequences-and-sequencing.html) (For Tuesday, DNA Sequences and Sequending)
2. Watch the Illumina Video embellished by Eric's captions here:
[https://eriqande.github.io/erics-captioned-vids/vids/illumina-sbs/](https://eriqande.github.io/erics-captioned-vids/vids/illumina-sbs/)
3. [eca-bioinf-handbook](https://eriqande.github.io/eca-bioinf-handbook/bioinformatic-file-formats.html) (For Tuesday: Sequences and FASTQ)
3. [eca-bioinf-handbook](https://eriqande.github.io/eca-bioinf-handbook/bioinformatic-file-formats.html) (For Thursday: FASTA and SAM)

## Recommended Readings {-}

* The [SAM specification](https://samtools.github.io/hts-specs/SAMv1.pdf) PDF

## Exercises due by 5:00 PM, Monday, February 10, 2020 {-}

I have put all the questions into an Rmarkdown document called "homework-questions.Rmd" inside a repository distributed by GitHub Classroom.  Get your own repository of it with this link:

[https://classroom.github.com/a/wYsku1TN](https://classroom.github.com/a/wYsku1TN)

This just provides a place to write your answers and submit them by commit and pull request by Monday, Feb 10, at 5 PM.  

---





